"""
examples.main_generator
~~~~~~~~~~~~~~~~~~~~~~~

Demonstrates how to consume visual event streams naturally using the Python 
Generator/Iterator interface. It hooks the VisionBridge events directly into 
a heavy-duty reasoning model.
"""

import sys
import os
import time

# Ensure parent package is in path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from vision_bridge import VisionBridgeModule

# Model settings
VLM_MODEL = "llama3.2-vision:1b"
REASONING_LLM_MODEL = "llama3:8b"


def consult_reasoning_llm(visual_description: str) -> str:
    """
    Simulates or calls the heavy reasoning model to take action based on the 
    lightweight text descriptions generated by the vision bridge.
    """
    try:
        import ollama
        
        prompt = (
            f"Context: A local camera sees '{visual_description}'. "
            "What immediate security or operational action should be logged?"
        )
        
        response = ollama.chat(
            model=REASONING_LLM_MODEL,
            messages=[{'role': 'user', 'content': prompt}]
        )
        return response['message']['content'].strip()
        
    except Exception as e:
        # Graceful fallback: simulate core LLM output if Ollama is offline/uninstalled
        return (
            f"[SIMULATED VERDICT] Action logged for: '{visual_description}'. "
            f"Reasoning: Trigger contains target event. (Ollama API unavailable: {e})"
        )


def main():
    # 1. Initialize the module (1 analysis per second, camera index 0)
    print("[VisionBridge Demo]: Initializing Vision Bridge Module...")
    vision_layer = VisionBridgeModule(
        vlm_model=VLM_MODEL,
        camera_index=0,
        frame_rate=1.0,
        provider="ollama"
    )

    # 2. Start the analysis loop with a filtering prompt
    filter_prompt = (
        "Look for objects or people. If a specific tool, person, or significant "
        "change is visible, state it clearly in 5 words or less. Otherwise reply 'None'."
    )
    
    vision_layer.start(prompt=filter_prompt)

    try:
        print("\n[System]: Listening for meaningful visual triggers...")
        print("[System]: Consuming events using standard Python Iterator pattern.")
        print("[System]: Press Ctrl+C to stop.\n")

        # 3. Yield and consume structured events as they arrive (Iterator Pattern)
        for event in vision_layer.get_events():
            visual_update = event.raw_text
            
            # Filter out empty or uninteresting frames
            if "none" in visual_update.lower():
                # Print a small indicator dot to show heartbeat activity
                print(".", end="", flush=True)
                continue

            print(f"\n\n[Trigger Event Detected]: {event}")
            print(f" -> VLM Latency: {event.response_time_ms:.1f}ms")
            print(" -> Consulting core reasoning engine...")

            # Pass structured text to a larger LLM for action
            verdict = consult_reasoning_llm(visual_update)
            print(f"\n🤖 [Core LLM Verdict]:\n{verdict}\n")

    except KeyboardInterrupt:
        print("\n[System]: Keyboard interrupt detected. Shutting down cleanly...")
    finally:
        # 4. Clean up resources
        vision_layer.stop()


if __name__ == "__main__":
    main()
